name: ğŸ—‘ï¸ Mark Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: ğŸ—‘ï¸ Mark Stale
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ—‘ï¸ Mark Stale
        uses: actions/stale@v10
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: |
            ğŸ‘‹ This issue hasn't had any activity in 60 days. It will be marked as stale and closed in 14 days unless it's updated.
            
            If you believe this is still relevant, please add a comment to keep it open.
          close-issue-message: |
            âŒ This issue was closed because it was inactive for 74 days.
          stale-pr-message: |
            ğŸ‘‹ This PR hasn't had any activity in 60 days. It will be marked as stale and closed in 14 days unless it's updated.
            
            If you believe this is still relevant, please add a comment to keep it open.
          close-pr-message: |
            âŒ This PR was closed because it was inactive for 74 days.
          remove-stale-when-updated: true
          ascending: false
